services:
  back:
    build:
      context: ../
      dockerfile: ./docker/back/Dockerfile
    container_name: back
    volumes:
      - ../back:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db
    stdin_open: true
    tty: true

  front:
    build:
      context: ../
      dockerfile: ./docker/front/Dockerfile
    container_name: front
    volumes:
      - ../front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - back

  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - ../.env
    volumes:
      - ~/goinfre/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"